query MyQuery {
  itemCollectionCollection {
    items {
      itemsCollection {
        items {
          ... on Data {
            question
            answer
          }
        }
      }
    }
  }
}